version: '3.8'

x-router-base: &router_base
  build:
    context: ./docker/roteador
    dockerfile: Dockerfile

x-host-base: &host_base
  build:
    context: ./docker/host
    dockerfile: Dockerfile

services:

  roteador1:
    <<: *router_base
    container_name: roteador1
    environment:
      - ROTEADOR_ID=roteador1
      - VIZINHOS={ "roteador6":["172.21.0.3",10],"roteador2":["172.21.1.2",10] }
    networks:

      rede1:
        ipv4_address: 172.21.0.2

      rede2:
        ipv4_address: 172.21.1.3


  roteador2:
    <<: *router_base
    container_name: roteador2
    environment:
      - ROTEADOR_ID=roteador2
      - VIZINHOS={ "roteador1":["172.21.1.3",10],"roteador3":["172.21.2.2",10] }
    networks:

      rede2:
        ipv4_address: 172.21.1.2

      rede3:
        ipv4_address: 172.21.2.3


  roteador3:
    <<: *router_base
    container_name: roteador3
    environment:
      - ROTEADOR_ID=roteador3
      - VIZINHOS={ "roteador2":["172.21.2.3",10],"roteador4":["172.21.3.2",10] }
    networks:

      rede3:
        ipv4_address: 172.21.2.2

      rede4:
        ipv4_address: 172.21.3.3


  roteador4:
    <<: *router_base
    container_name: roteador4
    environment:
      - ROTEADOR_ID=roteador4
      - VIZINHOS={ "roteador3":["172.21.3.3",10],"roteador5":["172.21.4.2",10] }
    networks:

      rede4:
        ipv4_address: 172.21.3.2

      rede5:
        ipv4_address: 172.21.4.3


  roteador5:
    <<: *router_base
    container_name: roteador5
    environment:
      - ROTEADOR_ID=roteador5
      - VIZINHOS={ "roteador4":["172.21.4.3",10],"roteador6":["172.21.5.2",10] }
    networks:

      rede5:
        ipv4_address: 172.21.4.2

      rede6:
        ipv4_address: 172.21.5.3


  roteador6:
    <<: *router_base
    container_name: roteador6
    environment:
      - ROTEADOR_ID=roteador6
      - VIZINHOS={ "roteador5":["172.21.5.3",10],"roteador1":["172.21.0.2",10] }
    networks:

      rede6:
        ipv4_address: 172.21.5.2

      rede1:
        ipv4_address: 172.21.0.3




  h1a:
    <<: *host_base
    container_name: h1a
    networks:
      rede1:
        ipv4_address: 172.21.0.10

  h1b:
    <<: *host_base
    container_name: h1b
    networks:
      rede1:
        ipv4_address: 172.21.0.11

  h1c:
    <<: *host_base
    container_name: h1c
    networks:
      rede1:
        ipv4_address: 172.21.0.12

  h1d:
    <<: *host_base
    container_name: h1d
    networks:
      rede1:
        ipv4_address: 172.21.0.13

  h1e:
    <<: *host_base
    container_name: h1e
    networks:
      rede1:
        ipv4_address: 172.21.0.14

  h1f:
    <<: *host_base
    container_name: h1f
    networks:
      rede1:
        ipv4_address: 172.21.0.15

  h2a:
    <<: *host_base
    container_name: h2a
    networks:
      rede2:
        ipv4_address: 172.21.1.10

  h2b:
    <<: *host_base
    container_name: h2b
    networks:
      rede2:
        ipv4_address: 172.21.1.11

  h2c:
    <<: *host_base
    container_name: h2c
    networks:
      rede2:
        ipv4_address: 172.21.1.12

  h2d:
    <<: *host_base
    container_name: h2d
    networks:
      rede2:
        ipv4_address: 172.21.1.13

  h2e:
    <<: *host_base
    container_name: h2e
    networks:
      rede2:
        ipv4_address: 172.21.1.14

  h2f:
    <<: *host_base
    container_name: h2f
    networks:
      rede2:
        ipv4_address: 172.21.1.15

  h3a:
    <<: *host_base
    container_name: h3a
    networks:
      rede3:
        ipv4_address: 172.21.2.10

  h3b:
    <<: *host_base
    container_name: h3b
    networks:
      rede3:
        ipv4_address: 172.21.2.11

  h3c:
    <<: *host_base
    container_name: h3c
    networks:
      rede3:
        ipv4_address: 172.21.2.12

  h3d:
    <<: *host_base
    container_name: h3d
    networks:
      rede3:
        ipv4_address: 172.21.2.13

  h3e:
    <<: *host_base
    container_name: h3e
    networks:
      rede3:
        ipv4_address: 172.21.2.14

  h3f:
    <<: *host_base
    container_name: h3f
    networks:
      rede3:
        ipv4_address: 172.21.2.15

  h4a:
    <<: *host_base
    container_name: h4a
    networks:
      rede4:
        ipv4_address: 172.21.3.10

  h4b:
    <<: *host_base
    container_name: h4b
    networks:
      rede4:
        ipv4_address: 172.21.3.11

  h4c:
    <<: *host_base
    container_name: h4c
    networks:
      rede4:
        ipv4_address: 172.21.3.12

  h4d:
    <<: *host_base
    container_name: h4d
    networks:
      rede4:
        ipv4_address: 172.21.3.13

  h4e:
    <<: *host_base
    container_name: h4e
    networks:
      rede4:
        ipv4_address: 172.21.3.14

  h4f:
    <<: *host_base
    container_name: h4f
    networks:
      rede4:
        ipv4_address: 172.21.3.15

  h5a:
    <<: *host_base
    container_name: h5a
    networks:
      rede5:
        ipv4_address: 172.21.4.10

  h5b:
    <<: *host_base
    container_name: h5b
    networks:
      rede5:
        ipv4_address: 172.21.4.11

  h5c:
    <<: *host_base
    container_name: h5c
    networks:
      rede5:
        ipv4_address: 172.21.4.12

  h5d:
    <<: *host_base
    container_name: h5d
    networks:
      rede5:
        ipv4_address: 172.21.4.13

  h5e:
    <<: *host_base
    container_name: h5e
    networks:
      rede5:
        ipv4_address: 172.21.4.14

  h5f:
    <<: *host_base
    container_name: h5f
    networks:
      rede5:
        ipv4_address: 172.21.4.15

  h6a:
    <<: *host_base
    container_name: h6a
    networks:
      rede6:
        ipv4_address: 172.21.5.10

  h6b:
    <<: *host_base
    container_name: h6b
    networks:
      rede6:
        ipv4_address: 172.21.5.11

  h6c:
    <<: *host_base
    container_name: h6c
    networks:
      rede6:
        ipv4_address: 172.21.5.12

  h6d:
    <<: *host_base
    container_name: h6d
    networks:
      rede6:
        ipv4_address: 172.21.5.13

  h6e:
    <<: *host_base
    container_name: h6e
    networks:
      rede6:
        ipv4_address: 172.21.5.14

  h6f:
    <<: *host_base
    container_name: h6f
    networks:
      rede6:
        ipv4_address: 172.21.5.15


networks:

  rede1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1

  rede2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/24
          gateway: 172.21.1.1

  rede3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.2.0/24
          gateway: 172.21.2.1

  rede4:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.3.0/24
          gateway: 172.21.3.1

  rede5:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.4.0/24
          gateway: 172.21.4.1

  rede6:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.5.0/24
          gateway: 172.21.5.1
