version: '3.8'

x-router-base: &router_base
  build:
    context: ./docker/roteador
    dockerfile: Dockerfile

x-host-base: &host_base
  build:
    context: ./docker/host
    dockerfile: Dockerfile

services:

  roteador1:
    <<: *router_base
    container_name: roteador1
    environment:
      - ROTEADOR_ID=roteador1
      - VIZINHOS={ "roteador2":["172.21.0.3",10],"roteador2":["172.21.0.3",10] }
    networks:

      rede1:
        ipv4_address: 172.21.0.2

      rede2:
        ipv4_address: 172.21.1.3


  roteador2:
    <<: *router_base
    container_name: roteador2
    environment:
      - ROTEADOR_ID=roteador2
      - VIZINHOS={ "roteador1":["172.21.1.3",10],"roteador1":["172.21.1.3",10] }
    networks:

      rede2:
        ipv4_address: 172.21.1.2

      rede1:
        ipv4_address: 172.21.0.3




  h1a:
    <<: *host_base
    container_name: h1a
    networks:
      rede1:
        ipv4_address: 172.21.0.10

  h1b:
    <<: *host_base
    container_name: h1b
    networks:
      rede1:
        ipv4_address: 172.21.0.11

  h2a:
    <<: *host_base
    container_name: h2a
    networks:
      rede2:
        ipv4_address: 172.21.1.10

  h2b:
    <<: *host_base
    container_name: h2b
    networks:
      rede2:
        ipv4_address: 172.21.1.11


networks:

  rede1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1

  rede2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.1.0/24
          gateway: 172.21.1.1
