networks:
- name: rede1
  subnet: 172.21.0.0/24
  gateway: 172.21.0.1
- name: rede2
  subnet: 172.21.1.0/24
  gateway: 172.21.1.1
routers:
- id: roteador1
  networks:
  - name: rede1
    ip: 172.21.0.2
  - name: rede2
    ip: 172.21.1.3
  neighbors:
  - id: roteador2
    cost: 10
  - id: roteador2
    cost: 10
- id: roteador2
  networks:
  - name: rede2
    ip: 172.21.1.2
  - name: rede1
    ip: 172.21.0.3
  neighbors:
  - id: roteador1
    cost: 10
  - id: roteador1
    cost: 10
hosts:
- name: h1a
  network: rede1
  ip: 172.21.0.10
- name: h1b
  network: rede1
  ip: 172.21.0.11
- name: h2a
  network: rede2
  ip: 172.21.1.10
- name: h2b
  network: rede2
  ip: 172.21.1.11
